Statistics
==========

{pmg} provides a useful and feature-rich statistics interface that allows
administrators to quickly get an overview of the overall workload and easily
identify problems.

The statistics are displayed for a selected period, which by default is the
current day. This period can be changed to any other day, a whole month or even
a whole year.

On the main statistics page there are three graphs with additional data:

'Total Mail Count'::

Shows the total mail flow as a graph and the following details:

* Total Mails
* Incoming/Outgoing Mails (as count and percentage)
* Virus Outbreaks (the amount of outgoing virus mails)
* Avg. Mail Processing Time
* Incoming/Outgoing Mail Traffic

'Incoming Mails'::

Displays the count of incoming mails from each of the following categories,
including their percentage of the total incoming mail volume:

* Incoming Mails
* Junk Mails (Virus + Spam + Greylisted + SPF rejects + RBL rejects)
* Greylisted Mails
* Spam Mails (Mails with Spamscore >= 3 and not containing a virus)
* SPF rejects
* Bounces (mails with an empty envelope-sender address)
* Virus Mails

'Outgoing Mails'::

Displays the count of outgoing mails from each of the following categories,
including their percentage of the total outgoing mail volume:

* Outgoing Mails
* Bounces (mails with an empty envelope-sender address)
* Virus Mails

Spam Scores
-----------

The `Spam Scores` panel shows the distribution of the different spam scores for
the selected time period. Note that you can also select a whole month or even a
whole year as period to display.

Virus Charts
------------

The `Virus Charts` panel shows which and how many viruses were detected in the
selected time period.

Hourly Distribution
-------------------

The `Hourly Distribution` shows the amount of incoming and outgoing mail per
hour for the selected time period. For periods spanning a whole month or a
whole year the arithmetic average of mail volume in an hour will be shown.

Postscreen
----------

Contains a chart with the RBL and pregreet rejects for the selected time frame.
For more info about postscreen and pregreet tests, see the
https://www.postfix.org/POSTSCREEN_README.html[postscreen readme].

Domain
------

The `Domain` view is split into two tabs, one for incoming and one for outgoing
mails. Each shows a summary grouped by the recipient domain in a selected time
frame, with stats for traffic, count, how many viruses were detected, and how
much of the mail volume was classified as spam.

Sender
------

The `Sender` panel contains a list of e-mail addresses that sent mail out in
the selected time frame, with a total count, how many viruses were detected and
how big these mails were.

If you click on one of these e-mail addresses, you see a detailed list of
recipients, complete with size, date and time.

Receiver
--------

Similar to the `Sender` panel, this contains a list of e-mail addresses that
received e-mails from outside, with a total, spam and virus count, as well
as the total mail size.

If you click an entry, it shows a detailed list of mails with size, date,
time, virus and spam score info.

If the `Use advanced statistics filters` option (`Configurations -> Options`)
is enabled, only active accounts will be listed. Active accounts are those that
sent mail during the selected time period or up to 90 days before.

Contact
-------

This contains the list of external recipients that received mail from this
{pmg}, coming in on the internal port, with total count, virus count and size.

If you click an entry, it shows a list of mails with size, date and time.

If the `Use advanced statistics filters` option (`Configurations -> Options`)
is enabled, active accounts will be filtered out, since they can already be
seen in the `Receiver` panel.  Active accounts are those which sent mail in the
selected time frame or up to 90 days before.
