[[installation_prepare_media]]
Prepare Installation Media
--------------------------

Download the installer ISO image from: {website}en/downloads/category/proxmox-mail-gateway

The {pmg} installation media is a hybrid ISO image. It works in two ways:

* An ISO image file ready to burn to a CD or DVD.

* A raw sector (IMG) image file ready to copy to a USB flash drive (USB stick).

Using a USB flash drive to install {pmg} is the recommended way, because it is
the faster option.

Prepare a USB Flash Drive as an Installation Medium
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The flash drive needs to have at least 1 GB of storage available.

NOTE: Do not use UNetbootin. It does not work with the {pmg} installation image.

IMPORTANT: Make sure that the USB flash drive is not mounted and does not
contain any important data.


Instructions for GNU/Linux
~~~~~~~~~~~~~~~~~~~~~~~~~~

On a Unix-like operating system, you can use the `dd` command to copy the ISO
image to the USB flash drive. To do this, find the device name of the USB
flash drive (see below), then run the `dd` command.

----
# dd bs=1M conv=fdatasync if=./proxmox-mailgateway_*.iso of=/dev/XYZ
----

NOTE: Be sure to replace /dev/XYZ with the correct device name and adapt the
input filename ('if') path.

CAUTION: Be very careful, and do not overwrite the wrong disk!


Find the USB Device Name
^^^^^^^^^^^^^^^^^^^^^^^^
There are multiple ways to find out the name of the USB flash drive. One is
to compare the last lines of the `dmesg` command output before and after
plugging in the flash drive. Another way is to compare the output of the
`lsblk` command. Open a terminal and run:

----
# lsblk
----

Then plug in your USB flash drive and run the command again:

----
# lsblk
----

A new device will appear. This is the one you want to use. As an additional
precaution, check that the reported size matches your USB flash drive.


Instructions for macOS
~~~~~~~~~~~~~~~~~~~~~~

Open the terminal (query Terminal in Spotlight).

Convert the .iso file to .img using the convert option of `hdiutil`, for
example:

----
# hdiutil convert -format UDRW -o proxmox-mailgateway_*.dmg proxmox-ve_*.iso
----

TIP: macOS tends to automatically add '.dmg' to the output filename.

To get the current list of devices, run the command:

----
# diskutil list
----

Now insert the USB flash drive and run this command again to determine which
device node has been assigned to it. (e.g., /dev/diskX).

----
# diskutil list
# diskutil unmountDisk /dev/diskX
----

NOTE: replace X with the disk number from the last command.

----
# sudo dd if=proxmox-mailgateway_*.dmg of=/dev/rdiskX bs=1m
----

NOTE: 'rdiskX', instead of 'diskX', in the last command is intended. This will
increase the write speed.

Instructions for Windows
~~~~~~~~~~~~~~~~~~~~~~~~

Using Etcher
^^^^^^^^^^^^

Etcher works out of the box. Download Etcher from https://etcher.io. It will
guide you through the process of selecting the ISO and your USB drive.

Using Rufus
^^^^^^^^^^^

Rufus is a more lightweight alternative, but you need to use the *DD mode* to
make it work. Download Rufus from https://rufus.ie/. Either install it or use
the portable version. Select the destination drive and the {pmg} ISO file.

IMPORTANT: After you 'Start', you have to click 'No' on the dialog asking to
download a different version of GRUB. In the next dialog select the 'DD' mode.

